version: "3.9"
services:
  nextjs:
    container_name: nextjs
    image: nextjs:0.0.1
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
    ports: # ポート番号のマッピング
      - 3000:3000
    restart: always # 再起動条件：常に
    tty: true
